# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(379, 490)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.name_input.setGeometry(QtCore.QRect(10, 10, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name_input.setFont(font)
        self.name_input.setText("")
        self.name_input.setAlignment(QtCore.Qt.AlignCenter)
        self.name_input.setObjectName("name_input")
        self.messages = QtWidgets.QTextBrowser(self.centralwidget)
        self.messages.setGeometry(QtCore.QRect(10, 50, 361, 371))
        self.messages.setObjectName("messages")
        self.text_input = QtWidgets.QTextEdit(self.centralwidget)
        self.text_input.setGeometry(QtCore.QRect(10, 430, 321, 31))
        self.text_input.setObjectName("text_input")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(340, 430, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.send_button.setFont(font)
        self.send_button.setObjectName("send_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pyChat"))
        self.name_input.setPlaceholderText(_translate("MainWindow", "Input your name, please"))
        self.text_input.setPlaceholderText(_translate("MainWindow", "Input your message here..."))
        self.send_button.setText(_translate("MainWindow", "^"))